### ISSUE TITLE
Licence for transformers in community version

### ISSUE THREAD

**Issue by kszpakowski** [Alfresco/alfresco-transform-core#184]
License displayed during start of every transformer requires written permission from Alfresco Software, is this agreement required for running community version, or it's part of enterprise version?

```
License rights for this program may be obtained from Alfresco Software, Ltd. pursuant to a written agreement and any use of this program without such an agreement is prohibited.
```

**Comment by kszpakowski** [comment]
@CezarLeahu Could you please help me understand this license notice? How does it relate to main GNU LGPL license?

**Comment by ascigajlo** [comment]
Regarding to the changes (https://github.com/Alfresco/alfresco-transform-core/commit/70652dcb3196e92f01657f11011c06d6bc76bcd7#diff-d90325ac7909f8e748022c6573d94bc8)  I have also a question about the licence. 

There is a lot of changes (57) in file's descriptions  i.e in file alfresco-docker-imagemagick/src/main/java/org/alfresco/transformer/Application.java was removed description: 
" * License rights for this program may be obtained from Alfresco Software, Ltd.
 * pursuant to a written agreement and any use of this program without such an
 * agreement is prohibited."

But the Application.startup() method still posses the old information from base package's class: StandardMessages
"String LICENCE =
        "License rights for this program may be obtained from Alfresco Software, Ltd. pursuant to a written agreement\n" +
        "and any use of this program without such an agreement is prohibited.\n" +
        "\n";"

I would like to ask: Is it correct situation or is it missing changes?

**Comment by montgolfiere** [comment]
AFAIK, the top-level https://github.com/Alfresco/alfresco-transform-core/blob/master/LICENSE.txt should apply. It should also be equivalent to other parts of the ACS Community (such as the Content Repository code base) including for example:

- https://github.com/Alfresco/alfresco-core
- https://github.com/Alfresco/alfresco-data-model
- https://github.com/Alfresco/alfresco-repository
- etc

The Java source code in this projects also has equivalent headers to above.

If you have any further questions, please feel to email contact info at bottom of:

https://www.alfresco.com/terms-use

I will also raise an internal ticket to see if we can get the startup info clarified (or removed) in the future, thanks.

**Comment by montgolfiere** [comment]
FYI: T-Engines 2.2.0-A2 and higher have fixed this issue.
