### ISSUE TITLE
ImageMagick maintainAspectRatio is inverted

### ISSUE THREAD

**Issue by nschwalbe** [Alfresco/alfresco-transform-core#191]
Doclib and imgpreview thumbnail in share are squares because the *maintainAspectRatio* has no effect anymore respectively is inverted.

In the OptionsBuilder the following if statement is wrong:
https://github.com/Alfresco/alfresco-transform-core/blob/46b2e6df5bd33ab0dd66817e7523ea43354cfac0/alfresco-docker-imagemagick/src/main/java/org/alfresco/transformer/OptionsBuilder.java#L342
It should be: `if (maintainAspectRatio == null || !maintainAspectRatio)`

Because the *!* means for imagemagick to force width and height.

**Comment by montgolfiere** [comment]
Yes, thank you. We have also had other similar feedback. Will update again once fix has been applied (& released).

**Comment by montgolfiere** [comment]
FYI: https://issues.alfresco.com/jira/browse/ATS-688

**Comment by montgolfiere** [comment]
JFYI: fixed by https://github.com/Alfresco/alfresco-transform-core/pull/195 (ready for next T-Core/T-Engines release)

**Comment by nschwalbe** [comment]
Thanks! :)
